# default configuration

[external.services.example]
baseURL = "http://www.google.com"
timeout = 25000

[http.api.paging]
defaultLimit = 20
defaultOffset = 0

[http.api.sorting]
defaultAttr = "created_on"
defaultOrder = "desc"

[http.server]
baseURL = "localhost"
mode = "debug"
namespace = "domain"
port = 9202
version = 1

[logger.app]
enabled = true
level = "info"

[logger.domain]
enabled = false
level = "info"

[logger.http]
enabled = true
level = "info"

[logger.repo]
enabled = true
level = "info"

[metadata]
path = "/app/package.json"

[postgres]
database = "svcdb"
host = "localhost"
password = "postgres"
port = 5432
user = "postgres"
