name: coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-golang-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Check out code
        uses: actions/checkout@v2

      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'

      - name: Build Image and Run Integration Tests
        run: docker compose run --rm api just coverage
      
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v1
        
      - name: Build Lambda Functions via AWS SAM
        run: etc/lambda/lambda_build.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./test/coverage/profile.cov

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.10.0
        with:
          files: test/coverage/junit.xml